### PR TITLE
README.md : Add badges, move intro line to top.

### PR DESCRIPTION
**Pull request by hasorli**
Badges: licence, docker, tweet, awesome agriculture badge

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks for the contributions @hasorli !

It looks like the Docker and Twitter badges are not working when I view the `patch-1` branch on your Github fork, though: https://github.com/hasorli/farmOS/tree/patch-1

If I load the images independently, they seem to work:

https://img.shields.io/twitter/url/http/shields.io.svg?style=social

https://img.shields.io/docker/pulls/farmos/farmos.svg

But not when rendered by Github, it seems.

Also, the Twitter badge links to @farmOSorg Twitter page (good) but the badge just says "Tweet" (sort of confusing?)

**Comment by mstenta** [comment]
I rebased the first commit of this pull request - modified it slightly but left the commit credit. Thanks again @hasorli !

I didn't include the second commit ("Add awesome agriculture badge") because it appears that list hasn't been officially merged into the awesome lists project yet: https://github.com/sindresorhus/awesome/pull/1316 - we can reassess this in the future if we want...

**Comment by mstenta** [comment]
https://github.com/farmOS/farmOS/commit/2eded9df738e80179f2504c193723c2f7593fc2f

**Comment by brycejohnston** [comment]
> I rebased the first commit of this pull request - modified it slightly but left the commit credit. Thanks again @hasorli !
> 
> I didn't include the second commit ("Add awesome agriculture badge") because it appears that list hasn't been officially merged into the awesome lists project yet: [sindresorhus/awesome#1316](https://github.com/sindresorhus/awesome/pull/1316) - we can reassess this in the future if we want...

That is cool on the awesome-agriculture badge. I just fixed some issues in the list where it should be merged into main awesome list soon. I'll post when it does. Thanks

**Pull request closed without merging**
