### PR TITLE
Use a test matrix to run tests and site-install against MariaDB/SQLite/Postgres in parallel

### PR DESCRIPTION
**Pull request by symbioquine**
**Why?** Detect if things break on specific DBMS' and have ongoing proof
that the top DB options work with farmOS.

### CODE REVIEW

**Comment by symbioquine** [comment]
I'm not sure what's going on here, the tests are [passing fine on my fork](https://github.com/symbioquine/farmOS/actions/runs/481634983) and the place it's failing shouldn't be affected by this change...

**Comment by symbioquine** [comment]
I've kicked off two more test runs to see if they are passing consistently for me...

* Run 2.x PHPUnit tests https://github.com/symbioquine/farmOS/actions/runs/481716584
* Run 2.x PHPUnit tests https://github.com/symbioquine/farmOS/actions/runs/481718187

**Comment by paul121** [comment]
@symbioquine the GH action doesn't work for pull requests right now.

I looked into it a little bit earlier but didn't go too far into the weeds.. it's because the action tries to checkout your branch from `origin`, but it doesn't exist. Should be OK if the tests pass on your fork!

**Comment by symbioquine** [comment]
Thanks @paul121! I didn't realize that...

**Comment by mstenta** [comment]
This is great @symbioquine - thanks for setting this up! Merged!

**Pull request closed without merging**
