### PR TITLE
Add 'owner' field to assets

### PR DESCRIPTION
**Pull request by jgOhYeah**
Hello,
This pull request adds an owner field to assets, based off the assign to functionality of logs.
For discussion and further details, please see here: https://farmos.discourse.group/t/is-it-possible-to-use-custom-fields-and-filtering-in-asset-views-and-filter-by-a-range-of-birth-dates/1139

# Note on installing and updating / why this shouldn't be merged just yet
Currently, attempting to install the updates to the `farm_owner` module using `update.php` causes `update.php` to crash (see [here](https://farmos.discourse.group/t/is-it-possible-to-use-custom-fields-and-filtering-in-asset-views-and-filter-by-a-range-of-birth-dates/1139/23) for @mstenta's investigations).

This does work when updated using drush or installing a fresh instance.

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks for working on all of this @jgOhYeah and opening this PR!

It looks like tests are failing due to some coding standards complaints from code sniffer: https://github.com/farmOS/farmOS/runs/6334229166?check_suite_focus=true

Also, would you mind cherry-picking your commits into a fresh branch off of the latest `2.x`, so that the two "Merge branch 'farmOS:2.x' into AssetOwners" commits are not included? If you're not sure how to do that it's OK - I can clean up/rebase later before we merge.

**Comment by mstenta** [comment]
Also needs a `CHANGELOG.md` entry (we can also wait on that until we're ready to merge too if you want).

**Comment by mstenta** [comment]
@jgOhYeah I have fixed the issue in the Entity API module patch that was blocking this. So if you can clean up the last bits then this will be ready for final review and merge!

https://www.drupal.org/project/entity/issues/3206703#comment-14512043

https://github.com/farmOS/farmOS/commit/d77145e17c9f7f9252ef34f2a0a5f4958a5cea6b

**Comment by jgOhYeah** [comment]
Thanks for fixing the Entity API patch issue. I will have a go at fixing various styling, documentation and merge issues in the next couple of days.

**Comment by jgOhYeah** [comment]
Apologies that it took so long. In the end I made a new branch and manually copied the changes across as in the end I found it easier than attempting to untangle a few of the botched merges in the views configs. I think I have addressed all codesniffer issues - we will see in a few minutes :). I can't see any failures caused by `farm_owner` in the unit tests, although I haven't added any new ones.

Hopefully this is in a mergeable state. If not, I can have a go at fixing it.
The new pull request is https://github.com/farmOS/farmOS/pull/537.

**Pull request closed without merging**
