### PR TITLE
Update to Drupal 10.2

### PR DESCRIPTION
**Pull request by paul121**
Updated a Drupal core patch [2339235](https://www.drupal.org/project/drupal/issues/2339235#comment-15382658) and got tests to pass, but have not tested this locally.

10.2.0 release notes: https://www.drupal.org/project/drupal/releases/10.2.0

I don't think there are any major changes to be worried about here....

> [Form elements in the stable9 base theme now have form-type-[form-element-type] class](https://www.drupal.org/node/3385635).

This could potentially affect some UI/CSS changes we have made, but seems unlikely.

### CODE REVIEW

**Comment by mstenta** [comment]
This LGTM! Can I merge it? Or did you leave it in draft for a reason?

> Remove time format from description 

Interesting. Does this change also fix https://github.com/farmOS/farmOS/issues/625, perhaps?

**Comment by mstenta** [comment]
> Does this change also fix https://github.com/farmOS/farmOS/issues/625, perhaps?

Nevermind, I don't think it fixes that issue, but removing the format is a good change because as we can see in those screenshots it is wrong most of the time anyway.

**Comment by paul121** [comment]
@mstenta and I chatted about this today and we feel pretty good. Should be fine to merge this and we could tag 3.0.0 stable soon after. If there are any issues, they can be fixed as we go.

**Review by mstenta — APPROVED** [review]
LGTM!

Also, 10.2.1 was released today, so I added a commit to update to that. And I found the 10.2.x patch you made here @paul121: https://www.drupal.org/project/drupal/issues/2339235#comment-15382708

Thanks!

**Review by mstenta — CHANGES_REQUESTED** [review]
Dang. Now tests are failing. :thinking:

```
There was 1 failure:

1) Drupal\Tests\farm_inventory\Functional\InventoryTest::testApiInventory
Failed asserting that an array is not empty.

/opt/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:121
/opt/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
/opt/drupal/web/profiles/farm/modules/core/inventory/tests/src/Functional/InventoryTest.php:111
/opt/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:728
```

**Comment by mstenta** [comment]
Huh. My test passed locally. But I'm running PostgreSQL and the failure was on SQLite3... :thinking:

**Comment by paul121** [comment]
Huh, I think I saw this same error when I first made this PR but re-ran tests and it passed.. maybe there is a new race condition of some kind. Not sure.

**Comment by mstenta** [comment]
Wow I think you're right @paul121. I ran tests 4 times, and it failed 3 times, but just now it passed once. So that suggests it is not 10.2.1 that's causing the problem. Huh. Well I guess we can merge this and tag 3.0.0 after all! We can figure out the test issue as a follow up...

**Pull request merged**
