### PR TITLE
Modified docker build process to be more containers friendly

### PR DESCRIPTION
**Pull request by sokoow**
This is not rebuilding every time container starts anymore. TODO: still have issues understanding why modules install on new installs, maybe related to database setup

### CODE REVIEW

**Comment by mstenta** [comment]
For anyone looking at this for the first time, please read https://github.com/farmOS/farmOS/issues/36 in full to understand the context and considerations.

**Comment by mstenta** [comment]
Also read @sokoow's other two recent issues that led to this pull request:

https://github.com/farmOS/farmOS/issues/132

https://github.com/farmOS/farmOS/issues/136

**Comment by mstenta** [comment]
As I said in https://github.com/farmOS/farmOS/issues/36 and https://github.com/farmOS/farmOS/issues/136, I am interested in taking an approach like this in the 8.x-2.x branch of farmOS, but I'm still not sure about merging it into 7.x-1.x - because it might be considered a BC breaking change (has the potential to break/disrupt existing deployments - but we should think this through in more detail to be sure). Let's discuss all the considerations here and decide how to proceed.

**Comment by mstenta** [comment]
Here is an outline of the main considerations (mainly copied from https://github.com/farmOS/farmOS/issues/36):

**Consideration 1: Backwards compatibility** - If the volume mount point does change, it will affect anyone who is running farmOS with Docker currently. See related comments here: https://github.com/farmOS/farmOS/issues/36#issuecomment-304022146 and https://github.com/farmOS/farmOS/issues/36#issuecomment-304023553

**Consideration 2: new installations** - Drupal comes with a `default.settings.php` file in `sites/default` that it automatically copies to `sites/default/setting.php` during the installation process (AFTER the container and codebase are built and running). If we build the codebase directly inside the image, and then mount `sites/default` as a volume, `default.settings.php` will not exist. This makes initial installation more difficult because it requires an additional step to create `settings.php` (this pull request is not handling this currently). See related comment here: https://github.com/farmOS/farmOS/issues/36#issuecomment-304024561

**Consideration 3: sites vs sites/default** - We may want to mount `/var/www/html/sites` into the container, rather than `/var/www/html/sites/default`. The `sites/all` directory is often used to put extra modules, themes, and libraries. This can also be done in `sites/default` though - so maybe defaulting to a `sites/default` volume is enough, and we can leave it to downstream users to decide if they want to mount `sites` instead, for more flexibility. (This is what https://github.com/farmOS/farmOS/issues/36 in general proposed.)

**Consideration 4: Drush, Drupal Console, Composer, etc** - If the `/var/www/html` directory is not mounted in a volume as a whole, then we no longer have the ability to mount it into other containers as well. Some examples where doing this is useful include command line build tools like Drush, Drupal Console, and PHP's Composer. If we want to use those tools with the codebase, they would also need to be installed directly inside the image. As it is now, we don't need to install those tools in the image, and they can be used separately via their own Docker images (eg: https://hub.docker.com/r/drush/drush, https://hub.docker.com/_/composer). Maybe this is a moot point, though - since it may make sense to include those in the container anyways (especially in farmOS 8.x-2.x). But are there other examples where we might need to be able to mount the whole `/var/www/html` directory into another container? Or should we just leave that up to the downstream user to configure their volumes differently than our repository default?

**Consideration 5: IDE development** - Similar to consideration 4 above, if the `/var/www/html` directory is not mounted in a volume as a whole, then it's not possible to use an IDE like PHPStorm for development of the codebase, because the IDE requires all of that code be accessible to it on the host (outside of the container).

**Consideration 6: production vs development** - The current way we have the Dockerfile, docker-compose.yml, and docker-entrypoint.sh scripts set up allows us to have two different approaches to deployment: one for production hosting using a tagged release, and one that checks out the git repo directly for development purposes. This pull request does look like it handles both of these still (similar to how it worked previously), but I'd like to give some thought to simplifying even further. Perhaps having two different Dockerfiles and/or docker-compose.yml files would be worth considering.

**Review by jasperboyd — APPROVED** [review]

**Comment by mstenta** [comment]
I've merged these changes in (https://github.com/farmOS/farmOS/commit/9234094ecb3960b529c9a36486eef140b8b11bcc), as well as a number of other changes (https://github.com/farmOS/farmOS/commit/38196e698e0cb3db62550e468423db56ee6115a3), to meet the goals of this pull request, and to address all the considerations I've outlined above.

The documentation on farmOS.org has been updated accordingly: https://farmos.org/development/docker/

Thanks for getting this started @sokoow !

**Pull request closed without merging**
