### PR TITLE
Do not trim whitespace from quantity field item content

### LINKED ISSUE #817: no commas in list of multiple materials, material quantity
image

### PR DESCRIPTION
**Pull request by mstenta**
This fixes #817.

I'm not sure if it's the "best" solution, but it was very simple, so I'm throwing it at the wall to see if it sticks. :-)

Curious your thoughts @paul121 since you were the original author of these lines. Were they copied from a core template?

### CODE REVIEW

**Comment by mstenta** [comment]
Before/after screenshots:

Screenshot from 2024-03-29 14-29-18

Screenshot from 2024-03-29 14-29-29

**Review by paul121 — COMMENTED** [review]
Interesting, this twig syntax is new to me. I believe I did copy this from somewhere in core.

I guess it works... but agree doesn't seem "best". What would it look like to clearly add a space within this loop? Add a "prefix" whenever it is not the 0th item?

I kind of like just using spaces but see how commas could be preferred

**Comment by mstenta** [comment]
> Interesting, this twig syntax is new to me. I believe I did copy this from somewhere in core.

Me too. I almost didn't notice it at first, and then had to look up what it meant.

> What would it look like to clearly add a space within this loop? Add a "prefix" whenever it is not the 0th item?

I'm not sure if there's any benefit to that over just allowing whitespace like this? :thinking: 

> I kind of like just using spaces but see how commas could be preferred

I thought about figuring out how to use commas, but this begs the question: do we use commas in other places?

All of those potential next steps vs this simple fix makes me wonder if we should just commit this to fix the "bug" and worry about "improvements" separately (and maybe more broadly).

**Review by paul121 — APPROVED** [review]
> All of those potential next steps vs this simple fix makes me wonder if we should just commit this to fix the "bug" and worry about "improvements" separately (and maybe more broadly).

Sounds good to me

**Pull request merged**
