### PR TITLE
Add helper functions for loading Crop and Crop Family terms.

### PR DESCRIPTION
**Pull request by paul121**
Adds two functions (not sure on the names - could they be better?)
- `farm_crop_families()`: Simple function to help load `farm_crop_families` terms.
- `farm_crop_families_crops()`: Load `farm_crop` terms that are apart of specific Crop Families. No parameter loads all Crop Terms.
  - Went with the `entity->load()` style where `ids = FALSE` specifies that all should be loaded. This requires a bit more logic, but seems cleaner than adding another parameter or needing a separate function to load all crop terms IMO. But open to alternatives!

Helps for building forms that use Crops + Varieties (named however you like haha :smile:):
crop_varieties

### CODE REVIEW

**Comment by mstenta** [comment]
Great thanks @paul121 !

> Adds two functions (not sure on the names - could they be better?)

Minor but: how about `farm_crop_family_crops()` instead of `farm_crop_families_crops()`?

**Comment by paul121** [comment]
That sounds better 👍 Any other changes I can make?

**Comment by mstenta** [comment]
Nope I think it looks good!

**Comment by paul121** [comment]
Force-pushed that change. Should be ready

**Comment by mstenta** [comment]
Done! Thanks again!

**Pull request merged**
