### PR TITLE
Fix Client error when passing asset parameter to forms

### LINKED ISSUE #813: Client error using the "Add log" bulk action
It seems that the "Add log" bulk action is broken. To reproduce, go to `/assets`, select an asset, select "Add log" from the actions dropdown, and then select "Observation". After submitting, you will see "Client error / A client error happened":

Originally reported here (with screenshot): https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/644

### PR DESCRIPTION
**Pull request by mstenta**
Fixes #813

### CODE REVIEW

**Review by paul121 — APPROVED** [review]
Interesting. This error does not happen if you use a query param like `&asset=25` as when using the "Add observation log" action button from a single asset page.

But this error does happen when appending brackets to potentially indicate multiple asset IDs `&asset[]=25`. I hadn't heard of this deprecation, just wonder where else this may apply...

**Comment by mstenta** [comment]
> query param like `&asset=25` as when using the "Add observation log" action button from a single asset page.

Oh good point @paul121.

I wonder if my fix breaks that case?

**Comment by mstenta** [comment]
> I wonder if my fix breaks that case?

Dang. Yes it does. Now I get "Client error" in that context.

**Comment by mstenta** [comment]
OK, I reworked the logic so that it works with both single value `asset` parameters as well as arrays.

It's a bit annoying because `$query->all('asset')` errors when it isn't an array and `$query->get('asset')` errors when it is an array. But `$query->all()` gives me a keyed array of ALL parameters, which I can use to get `asset` in both cases. 🙄

**Comment by mstenta** [comment]
This also needs to be fixed here: https://github.com/farmOS/farmOS/blob/3.x/modules/core/quick/src/Traits/QuickPrepopulateTrait.php#L77

**Review by paul121 — APPROVED** [review]

**Comment by mstenta** [comment]
Merged.

**Pull request closed without merging**
