### PR TITLE
Add docker-compose.yml and a gitignore for ignoring the data folder

### PR DESCRIPTION
**Pull request by rjcorwin**
This adds a `docker-compose.yml` file which allows us to get the farmOS container up and running with MySQL using Docker Compose (install instructions for Docker Compose [here](https://docs.docker.com/compose/install/)).

```
git clone git@github.com:farmos/farmos
cd farmos
docker-compose up -d
```

When you visit your server in the browser, you will be prompted to install and enter database information. Select mysql and set database name, username, and password to `farmos`.  Under  Andvanced Options, set Database host to `db`. 

This PR still needs some work though. Currently it will pull the Docker image for farm os from https://hub.docker.com/r/rjsteinert/farmos/ when ideally it will point to yet to be created https://hub.docker.com/r/rjsteinert/farmos/. @mstenta I created a farmos org on Docker Hub, go ahead and create an account for yourself and I'll add you as an owner. Then you will be able to set up an automated build for the `farmos/farmos` image because you have ownership over the github `farmos/farmos` repository.  At that point, we modify the `docker-compose.yml` file to point to that new image on Docker Hub.

### CODE REVIEW

**Comment by rjcorwin** [comment]
Also note, having the database username and password always `farmos` might seem like a security hole, it might be, but in general this shouldn't be an issue because mysql is not available over any port to the outside world, only port 80 inside the container is mapped to port 80 on the host machine.

**Comment by rjcorwin** [comment]
The `docker-compose.yml` file is inspired by the [Wordpress example](https://docs.docker.com/compose/wordpress/) for this kind of file.

**Comment by thedude459** [comment]
I am getting errors on the on all the ADDS that you have in the docker file.  I put a pull request in for a docker file that takes out the ADDs and just does a git to the repo for the files.  Not sure if you just want to merge the two docker files.

**Comment by thedude459** [comment]
#11

**Comment by mstenta** [comment]
Awesome! Thanks @rjsteinert and thanks @thedude459 for #11 

@rjsteinert I created a Docker Hub account - thanks for setting that up! What do I need to do on my end? https://hub.docker.com/u/mstenta

I installed docker-compose and used the commands in comment 1. It worked on the first try! I was able to get into the farmOS installer no problem. It is painfully slow, though... not sure why... any ideas? It takes a LOOOONG time to do anything. Maybe something isn't set up right with my containers?

A bunch of Drupal error messages are present throughout... but I think we can safely ignore them. They are related to PHP 7 support in the Ctools module - which is already fixed upstream. Created a new bug report here for that specifically: https://www.drupal.org/node/2785215

One other thing we should add is the GEOS library, but I don't think that is a prereq for this. See https://github.com/farmOS/farmOS/issues/12

It seems to work great, otherwise! Very cool!

**Comment by mstenta** [comment]
Oh also, it looks like the libraries defined in the build-farm.make file were not added. Hmm. See attached screenshot. http://imgur.com/wDlXfFY

**Comment by mstenta** [comment]
I added some instructions to for setting up a local development environment using Docker Compose to the farmOS.org docker branch: https://github.com/farmOS/farmOS.org/issues/14

It is not live yet (on farmOS.org) - we can merge it in once this pull request is merged.

@rjsteinert and @thedude459 can you test my instructions to see if they work for you? Anything else you want to add to them?

**Comment by mstenta** [comment]
Here is the comparison of the docker branch, so you can read the new documentation directly: https://github.com/farmOS/farmOS.org/compare/docker

**Comment by thedude459** [comment]
The instructions look good.  I updated the dockerfile and pushed it to the repo.

**Comment by thedude459** [comment]
#13 I also add the GEOS library to the docker.  Please test if the functionality that needed that library is working.

**Comment by rjcorwin** [comment]
@mstenta I added you to the Docker Hub farmOS organization. Log into Docker Hub and create and automated build for the farmos/farmos repo on Github and place that into the farmos org on Docker Hub. If you need a hand setting that up feel free to ping me tomorrow. There are some best practices around the automated build settings that would be easier to explain over a hangout than on this issue.

screen shot 2016-08-18 at 9 40 48 pm

**Comment by thedude459** [comment]
I think you should merge this pull and we can go from there.  That way you can setup the autobuilds like @rjsteinert said.

**Comment by thedude459** [comment]
I closed my pull request.

**Comment by mstenta** [comment]
Agreed - let's get this merged! First I think we just need to make one last update...

@rjsteinert I created an automated build on Docker Hub. Can you take a look and make sure I did it right?

https://hub.docker.com/r/farmos/farmos

Then I think the only remaining thing to do is change "rjsteinert/farmos" to "farmos/farmos" in the docker-compose.yml file, correct?

**Comment by thedude459** [comment]
@mstenta I assume we can't upgrade to docker 8 for this correct?

**Comment by mstenta** [comment]
> @mstenta I assume we can't upgrade to docker 8 for this correct?

@thedude459 - I'm not sure I understand... docker 8?

**Comment by thedude459** [comment]
@mstenta sorry I meant drupal 8.

**Comment by mstenta** [comment]
@thedude459 Oh gotcha! That makes more sense. :-)

Yea, we have plans for an 8.x-2.x branch of farmOS: https://www.drupal.org/node/2361735

I'm eager to get the balls rolling on that. The sooner we can get onto 8, the sooner we can start working on some of the really cool features on the list. There are some big steps to take, though. Notably: the Openlayers module needs an 8 version. And we will need to provide migration logic to help move 7.x-1.x farmOS sites to 8.x-2.x.

**Comment by thedude459** [comment]
@rjsteinert could you explain what the .gitignore file is doing?  Where is the data folder that will be ignored?

**Comment by mstenta** [comment]
@thedude459 The docker-compose.yml file sets up a .data folder to store the database in, so that it is preserved when the container is destroyed:

```
volumes:
  - "./.data/db:/var/lib/mysql"
```

**Comment by thedude459** [comment]
@mstenta that makes sense, thank you.  I think you should merge this as is and we can change the docker repo in the compose file once the docker repo is setup.

**Comment by thedude459** [comment]
@rjsteinert and @mstenta I know farmOS already has alot of subrepos but does it make sense to have a farmOS/farmOS-docker repo specifically for docker related items?

**Comment by mstenta** [comment]
@thedude459 Yea I'm eager to get this in too. RJ and I did a Google Hangout yesterday to work through a few remaining things.

For one, we now have an official Docker Hub repo for farmOS, which is super cool! https://hub.docker.com/r/farmos/farmos/

The one remaining thing I'm trying to figure out now is how to properly preserve Drupal's sites/default/files and sites/default/private directories outside of the Docker container, otherwise they are lost when you destroy and rebuild the container - which means you can't upgrade farmOS by simply fetching the new image.

There's a bunch of discussion on this topic here: https://github.com/docker-library/drupal/issues/3 - I'm currently reading through that...

**Comment by mstenta** [comment]
@thedude459 Regarding a separate repo for Docker-related stuff... that's an idea... the same thought came to mind for me too. I think for right now we should keep it in the 7.x-1.x of the farm distribution - but we will have the opportunity to reconsider that with the 8.x-2.x branch, if it seems like too much to manage in the same repo. So far, though, I don't think it will be. We shall see! :-)

**Comment by thedude459** [comment]
@mstenta do you only need those two folders?

**Comment by mstenta** [comment]
@thedude459 Technically for a farmOS install you only need the one "files" folder. Private files are not used by default, but it is possible to change that from within Drupal, so it should be included here too.

We will probably also mount sites/all/modules as a volume, which will allow you to add contrib modules that don't come with farmOS (ie: the Beekeeping module if you keep bees: http://drupal.org/project/farm_bee). This may also be useful for doing development on farmOS modules because you could theoretically just put the Git working copy of a module in that folder and it will override the one that comes with farmOS in profiles/farm/modules. All still theory... but I have some commits in a local branch (including RJ's commit that adds the docker-compose.yml) that I'm testing now.  I need to do some other stuff today, so I might not get to try everything but I will post full results soon...

**Comment by mstenta** [comment]
In general, it sounds like a lot of these things are still being figured out in https://github.com/docker-library/drupal/issues/3 - so we'll need to keep an eye on that and see what comes of it. I've subscribed to that issue.

**Comment by thedude459** [comment]
Should be as easy as adding volumes under the farmos part of the docker-compose file.  That is how all the other dockers I have work.

**Comment by mstenta** [comment]
Yea seems pretty straightforward! This is what I'm working with right now:

```
image: farmos/farmos:7.x-1.x
volumes:
  - "./.data/files:/var/www/html/sites/default/files"
  - "./.data/private:/var/www/html/sites/default/private"
  - "./.data/modules:/var/www/html/sites/all/modules"
```

**Comment by mstenta** [comment]
One thing to note: it seems that there is an extra step involved... you need to change the ownership of those folders after running `docker-compose up -d` so that they are writable by Drupal:

```
sudo chown -R www-data:www-data .data/files .data/private .data/modules
```

Maybe there's a better way to do this...

**Comment by mstenta** [comment]
Another thing I'm finding: it's possible to access the farmOS container simply by going to 127.0.0.1 (@rjsteinert showed me this) - but for some reason it is not able to connect to the database for installation on that IP (see possible related issue in Wordpress Docker queue here: https://github.com/docker-library/wordpress/issues/89).

If, however, I go to the actual container IP (in my case: 172.18.0.3), then it DOES connect to the db container.

The weird thing is... once farmOS is installed - I can access it just fine from 127.0.0.1 - and the database connection works as expected. I don't understand that...

Also, I'm finding that everything is EXTREMELY slow - especially installation.

**Comment by mstenta** [comment]
Alright, I need to work on some other things now... so it's off the computer for me. :-)

I pushed my current work to a new branch called "docker": https://github.com/farmOS/farmOS/compare/docker

It includes the original commit from this pull request (thanks again @rjsteinert ) - and three commits that I added:
1. Change Docker hub repo to farmos/farmos:7.x-1.x
2. Mount volume for sites/default/files
3. Mount volume for sites/all/modules

Let's continue working from that branch. I'm going to start a new issue for discussion because this one is getting long, and we can use it to focus on the remaining pieces before merging it into 7.x-1.x. For now, you can test by pulling down the "docker" branch locally and running `sudo docker-compose up -d`

**Comment by mstenta** [comment]
Ok, here's the new official Docker discussion issue: https://github.com/farmOS/farmOS/issues/15

Let's continue the conversation over there... I'll post the remaining issues and questions that I see as of right now. Feel free to add to it.

**Pull request closed without merging**
