### PR TITLE
Single Dockerfile using multi-stages for production and dev image

### PR DESCRIPTION
**Pull request by AlMaVizca**
This proposal is reorganizing the instructions to get advantage of the Docker cache, and handle a single file for images

### CODE REVIEW

**Comment by AlMaVizca** [comment]
@mstenta @paul121 It seems that the tests are failing due to another non-related error.
Please let me know your thoughts, or how do you want to proceed, thanks.

**Comment by mstenta** [comment]
@AlMaVizca Hmm it looks like these test failures are specific to this PR. They aren't happening on the 3.x branch currently: https://github.com/farmOS/farmOS/actions

Maybe the easiest thing to do is create a new testing branch (separate from this PR branch) and push one commit at a time to your fork to see which change causes the issue. This also helps to ensure each commit is a self-container non-breaking change.

**Comment by mstenta** [comment]
FYI: If you prefix your branch name with `3.x-`, then the GitHub Action will automatically run tests on your fork. So you can test stuff outside of the PR before bringing them back here.

**Comment by AlMaVizca** [comment]
Closed in favor of #751

**Pull request closed without merging**
