### PR TITLE
Delete data when basic data streams are deleted. Fixes #488

### LINKED ISSUE #488: Data is not deleted when a data stream entity is deleted
Steps to reproduce:

1. Create a sensor asset.
2. Copy `curl` command from "Developer information" and run it to post a data point.
3. Delete the `data_stream` entity that was created (need to disable entity reference integrity constraint first, see #485)
4. Look in the database, the data is still there.

### PR DESCRIPTION
**Pull request by mstenta**
See #488

### CODE REVIEW

**Review by paul121 — CHANGES_REQUESTED** [review]
It seems that we had this when we had a separate `legacy` data stream bundle, but the `hook_data_stream_delete` implementation got dropped with this commit: https://github.com/farmOS/farmOS/commit/e528813330b58faa09282e8b8e5b71385f19c902

We should add a test for this so we don't forget it in the future.

This PR is nearly identical to the original code though, so LGTM otherwise!

```php
function farm_sensor_listener_data_stream_delete(DataStreamInterface $data_stream) {

  // Remove all legacy listener data provided by the data stream.
  if ($data_stream->bundle() == 'legacy_listener') {
    \Drupal::database()->delete('data_stream_legacy')
      ->condition('id', $data_stream->id())
      ->execute();
  }
}
```

**Comment by paul121** [comment]
Added a test for this!

In the process, noticed that we have the logic for removing references to data streams in the wrong place, it should be in farm_sensor. Moved the logic and added another test for this, but running into the entity reference integrity issue... so I marked the test to be skipped for now, but this still causes our test runner to fail. Gotta run but wanted to push here for now...

**Comment by mstenta** [comment]
Thanks @paul121! I separated this into two branches...

1. `2.x-delete-data-stream-data` with my original commit + your test for deleting data
2. `2.x-data-stream-references` with your two commits re: asset reference fields

I'll point to (2) from https://github.com/farmOS/farmOS/issues/485...

Running tests on this PR (`2.x-delete-data-stream-data`) now... I will merge if it passes.

**Comment by mstenta** [comment]
Ah tests failed because `SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "test36388637asset__data_stream" does not exist` - this is probably what you ran into, huh @paul121 :-)

Whelp... I suppose we can just delete that original code from `hook_ENTITY_TYPE_delete()` (which is causing the test to fail), since we discovered in #485 that it isn't working as intended anyway (and maybe we'll end up taking a different approach to solve that issue, removing the need for that code).

**Comment by paul121** [comment]
Precisely - that's perfect!

**Pull request merged**
