### PR TITLE
Update Drupal core to 9.2.8 and remove the core patch that was merged upstream.

### PR DESCRIPTION
**Pull request by mstenta**
See https://www.drupal.org/project/drupal/issues/3192365

This cannot be merged until Drupal 9.2.8 is released.

### CODE REVIEW

**Comment by symbioquine** [comment]
LGTM!

In case anyone else has the same confusion; the conclusion that it wasn't in 9.2.7, but will be in 9.2.8 wasn't totally intuitive to me until I found [this page](https://git.drupalcode.org/project/drupal/-/network/9.2.x):

image

**Comment by mstenta** [comment]
FYI: Drupal 9.2.8 shouild be released on Wednesday, November 3rd.

https://www.drupal.org/docs/understanding-drupal/understanding-drupal-version-numbers/when-is-the-next-release

> A bug fix (patch) release window is on the first Wednesday of each month

I'll add that to my calendar so I remember to merge this.

**Comment by mstenta** [comment]
Drupal 9.2.8 has been released: https://www.drupal.org/project/drupal/releases/9.2.8

**Comment by mstenta** [comment]
This also required an update to the `drupal/core` patch for [Issue #2429699: Add Views EntityReference filter to be available for all entity reference fields](https://www.drupal.org/project/drupal/issues/2429699)

I had tested this patch previously, and even accidentally [committed](https://github.com/farmOS/farmOS/commit/f69640bde6083c849133850d0557c2c8466ebb9f) it prematurely to the `2.x` branch, which I then [reverted](https://github.com/farmOS/farmOS/commit/5da75606a196460463c79e01a10b49c2829c680b), so I was able to just [cherry-pick](https://github.com/farmOS/farmOS/commit/9f212bca297c65b612bdcab632735e1743423c86) my first commit again.

**Pull request merged**
