### PR TITLE
Only change the www-data ID right before it is needed.

### PR DESCRIPTION
**Pull request by paul121**
This change decreases the docker dev image build time when only changing the user ID. It allows the docker layers including the xdebug installation to be reused since they are not dependent nor installed by the www-data user.

See https://docs.docker.com/engine/reference/builder/#impact-on-build-caching

### CODE REVIEW

**Comment by paul121** [comment]
Interestingly, I don't think the effects of this change will be visible on here until the upstream farmOS/farmOS:2.x-dev docker image is rebuilt with this change. But if the docker image is built locally (with caching enabled) then the change will be visible.

**Comment by paul121** [comment]
Hmmm... after building locally with the default, then running:

```
docker build   --build-arg WWW_DATA_ID="2000"   farmOS/docker/dev   -t farmos/farmos:2.x-dev
```

just got the following:

```
Step 7/18 : RUN yes | pecl install xdebug       && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
 ---> Running in 271939e90824
pecl/xdebug is already installed and is the same as the released version 3.1.1
install failed
The command '/bin/sh -c yes | pecl install xdebug       && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini' returned a non-zero code: 1
```

**Comment by paul121** [comment]
Ah, seems to be working. A better test:

```bash
$ docker image prune -a
$ docker build farmOS/docker/dev -t farmos/farmos:2.x-dev
... runs normally
$ docker build   --build-arg WWW_DATA_ID="2000"   farmOS/docker/dev   -t farmos/farmos:2.x-dev
Sending build context to Docker daemon  6.656kB
Step 1/18 : FROM farmos/farmos:2.x
 ---> 43c164f133db
Step 2/18 : ARG FARMOS_REPO=https://github.com/farmOS/farmOS.git
 ---> Using cache
 ---> 002550ce0ac3
Step 3/18 : ARG FARMOS_VERSION=2.x
 ---> Using cache
 ---> 70f0dbe6ecd5
Step 4/18 : ARG PROJECT_REPO=https://github.com/farmOS/composer-project.git
 ---> Using cache
 ---> b4ced1580648
Step 5/18 : ARG PROJECT_VERSION=2.x
 ---> Using cache
 ---> 50a5b6aa7f48
Step 6/18 : RUN sed -i 's|opcache.revalidate_freq=60|opcache.revalidate_freq=0|g' /usr/local/etc/php/conf.d/opcache-recommended.ini
 ---> Using cache
 ---> d3d17eb05c29
Step 7/18 : RUN yes | pecl install xdebug       && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
 ---> Using cache
 ---> ba7fabd72d5c
Step 8/18 : ARG WWW_DATA_ID=1000
 ---> Using cache
 ---> bf1cf7f81edb
Step 9/18 : RUN usermod -u ${WWW_DATA_ID} www-data && groupmod -g ${WWW_DATA_ID} www-data
 ---> Running in 6a8ffd7acbf8
 ```

**Comment by mstenta** [comment]
Makes sense - thanks @paul121! Merged: https://github.com/mstenta/farmOS/commit/59673a5b6405fb60e40d5686003dbd23f3f43b70

**Pull request closed without merging**
