### PR TITLE
Issue #3335267: 405 Method Not Allowed when trying to patch entities as a user with non-default language

### PR DESCRIPTION
**Pull request by mstenta**
See https://www.drupal.org/project/farm/issues/3335267

### CODE REVIEW

**Review by symbioquine — APPROVED** [review]
My only nits to pick here are:

* Is it worth adding a test for this?
* I'd personally put more of the "Proposed resolution" description from the Drupal issue into the commit message itself.

Otherwise, LGTM - pending manual testing by @Farmer-Eds-Shed

**Comment by mstenta** [comment]
> Is it worth adding a test for this?

Yes it probably is. I'll set the status to "Needs work" on the d.o issue and mention that...

> I'd personally put more of the "Proposed resolution" description from the Drupal issue into the commit message itself.

Makes sense. I generally think that as long as the issue number is referenced in the commit message, that is the best link back to the full context and reasoning. That covers `git blame` forensics. But even `git blame` history can become lost/fragmented over time as things change or move around, so in this case I thought it worth also linking back to the original issue in a code comment directly:

https://github.com/farmOS/farmOS/pull/629/files#diff-3846dce09e5e8e499c65c7337a81d86c0edd9535592c6d023e28555e7e55e588R36

But that's just my convention. :-)

**Comment by mstenta** [comment]
FWIW I probably won't have time to write tests for this right away... so if anyone wants to pick that up feel free! I'll post an update when I'm able to, if no one else has in the meantime.

**Comment by Farmer-Eds-Shed** [comment]
Looks good,
I tried a few different log an asset types with no issues.

**Comment by mstenta** [comment]
Force pushed this branch with one additional commit before the original commit, which adds kernel tests that demonstrate the issue. The tests fail without the fix commit.

Note that this depends on #638, so it includes all of the commits from that branch too. We should get that merged first, and then review this.

**Comment by mstenta** [comment]
Reviewed with @paul121 - this is ready to merge.

**Pull request merged**
