### PR TITLE
Add farm_report module, simple CSV export of animal weights, simple graph of animal weights.

### PR DESCRIPTION
**Pull request by paul121**
- farm_livestock_weight adds a simple graph of animal weights under the "Weight" tab
- farm_report adds a "Reports" tab to the Dashboard menu
- farm_livestock_weight adds an "Animal Weights" report, exports CSV of animal weights from selected groups

### CODE REVIEW

**Comment by paul121** [comment]
The "Reports" tab - 
csv_export_tab

Simple CSV Export report form -
csv_export_form

Sample animal report CSV file -
csv_export_file

**Comment by mstenta** [comment]
FYI I rebased and renamed this branch to `weight_reports` in my fork. Check that branch out locally, then reset your `7.x-1.x` branch to it, then force push to your fork - and that should update this PR automatically so it knows where the new work is.

**Comment by paul121** [comment]
Thanks @mstenta ! I made the two changes we discussed.
- Changed the format of the CSV
- Unset the start date in the form
- I also modified the default date_year_range to be -10 years to +1 years. Is that sufficient?

**Comment by mstenta** [comment]
Great!  Testing it out now - the new columns look good in the CSV! And unsetting the start date works. -10/+1 years sound good to me.

One issue I'm seeing in my test site: I have an animal that has two weight logs. I see both sets of columns in my CSV, but only the first one has data in it. See attached, and screenshot of my animal's weight logs.

[animal_weights.txt](https://github.com/farmOS/farmOS/files/3461969/animal_weights.txt)

Screenshot from 2019-08-02 11-42-56

The only thing I can think that might be weird about it is that the second weight log (July 24th) references TWO assets (Child test 1, Test animal 1). Could that be causing it?

**Comment by mstenta** [comment]
Oh actually... now that I look closer... the first weight in the CSV is wrong too. It should be 150 lbs, but it says 100 lbs.

**Comment by paul121** [comment]
Hmmm. I didn't do any testing for logs with multiple assets. I guess I'm
not fully sure how that works - is a separate log not created for each
asset? Right now I loop through each asset, then collect all weight logs
associated with each asset. That is what populates the dates in CSV
header... Interesting that the 7/24 date is there, but the values aren't.

Also it looks like log #36 was 100 pounds, #37 was 150. I probably have it
taking the the first log recorded on a date, not the last log recorded.
Should I switch that?

**Comment by mstenta** [comment]
> I didn't do any testing for logs with multiple assets. I guess I'm
not fully sure how that works - is a separate log not created for each
asset?

It's possible to create a single weight log that references multiple assets. But if you are just iterating through assets and loading all weight logs for each, then it should pick it up. It seems like it did... at least partly... because it created the column, albeit didn't fill in the values.

> Also it looks like log #36 was 100 pounds, #37 was 150. I probably have it
taking the the first log recorded on a date, not the last log recorded.
Should I switch that?

Yea generally in farmOS we go by the latest log in cases like that... and if two logs have the same timestamp, we go by the one with the higher log ID.

**Comment by paul121** [comment]
OK - I believe these issues are fixed. Both stemmed from how I was "collecting" the dates. I was using a global array of dates instead of one unique to each animal. Attempted duplicates were dropped for animals if another had already claimed a date.

Now, being unique to each animal, only duplicate log dates for the same animal are dropped. And because `farm_quantity_log_data` loads logs in descending order, the most recent log comes first followed by older ones on the same date, which get dropped.

**Comment by mstenta** [comment]
Finally got around to merging this.

https://github.com/farmOS/farmOS/commit/f13327f584735991d8a0dd0b689648c927db7fda

Thanks again @paul121 !

**Pull request closed without merging**
